version: '2'

services:

    redis-cache:
        image: redis:alpine
        container_name: opac_redis_prod
        user: redis
        restart: always
        volumes:
            - redis-data:/data
            - /etc/localtime:/etc/localtime:ro

    opac_mongo:
        image: mongo:4.2
        container_name: opac_mongo_prod
        restart: always
        user: mongodb
        hostname: opac-mongo
        ports:
            - "27017:27017"
        volumes:
            - mongodb-data:/data/db:rw

    opac_webapp:
        image: infrascielo/opac_5
        container_name: opac_webapp_prod
        user: opac
        restart: always
        hostname: opac_webapp
        depends_on:
            - opac_mongo
            - redis-cache
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - opac_webapp-data:/app
        links:
            - opac_mongo:opac-mongo
            - redis-cache:redis-cache
        expose:
            - "8000"
        environment:
            - OPAC_DEBUG_MODE=False
            - OPAC_LOG_LEVEL=WARNING
            - OPAC_MINIFY_PAGE=False
            - OPAC_MONGODB_NAME=opac
            - OPAC_DATABASE_DIR=/app/data
            - OPAC_SECRET_KEY=s3kr3tk3y
            - OPAC_MONGODB_HOST=opac_mongo
            - OPAC_CACHE_ENABLED=True
            - OPAC_CACHE_DEFAULT_TIMEOUT=3600
            - OPAC_CACHE_REDIS_HOST=redis-cache
            - OPAC_USE_METRICS=True
            - OPAC_METRICS_URL=http://analytics.scielo.org
            - OPAC_USE_DIMENSIONS=True
            - OPAC_DIMENSIONS_URL=https://badge.dimensions.ai/details/doi
            - OPAC_USE_PLUMX=True
            - OPAC_PLUMX_METRICS_URL=https://plu.mx/scielo/a
            - OPAC_USE_ALTMETRIC=True
            - OPAC_ALTMETRIC_METRICS_URL=https://www.altmetric.com/details.php
            - OPAC_JOURNAL_PAGES_SOURCE_PATH=/app/data/pages
            - OPAC_JOURNAL_IMAGES_SOURCE_PATH=/app/data/img
            - OPAC_APM_ENABLED=False
            - OPAC_APM_SERVER_URL=
            - OPAC_APM_SERVICE_NAME=Website
            - OPAC_APM_ENVIRONMENT=production
            - OPAC_APM_SECRET_TOKEN=
            - OPAC_SSM_SCHEME=http
            - OPAC_SSM_DOMAIN=minio
            - OPAC_SSM_PORT=9000
            - OPAC_FILTER_SECTION_ENABLE_FOR_MIN_STUDY_AREAS=5
            - OPAC_FILTER_SECTION_ENABLE=True

    nginx:
        image: nginx:latest
        container_name: opac_nginx
        depends_on:
            - opac_webapp
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/logs:/var/log/nginx/
        ports:
            - "80:80"

    opac-rq-worker-1:
        image: infrascielo/opac_5
        container_name: opac_rq_worker_prod
        command: /app/start_worker.sh
        user: opac
        restart: always
        depends_on:
            - opac_mongo
            - redis-cache
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - opac_webapp-data:/app
        links:
            - opac_mongo:opac-mongo
            - redis-cache:redis-cache
        environment:
            - OPAC_DEBUG_MODE=False
            - OPAC_MONGODB_NAME=opac
            - OPAC_DATABASE_DIR=/app/data
            - OPAC_SECRET_KEY=s3kr3tk3y
            - OPAC_MONGODB_HOST=opac-mongo
            - OPAC_CACHE_ENABLED=True
            - OPAC_CACHE_DEFAULT_TIMEOUT=3600
            - OPAC_CACHE_REDIS_HOST=redis-cache
            - OPAC_SERVER_NAME=opac.scielo.org
            - OPAC_AUDIT_LOG_NOTIFICATION_ENABLED=True
            - OPAC_AUDIT_LOG_NOTIFICATION_RECIPIENTS=foo@scielo.org,bar@scielo.org
            - OPAC_RQ_REDIS_HOST=redis-cache
            - OPAC_RQ_REDIS_PORT=6379

    opac-rq-scheduler:
        image: infrascielo/opac_5
        container_name: opac_rq_scheduler_prod
        command: /app/start_scheduler.sh
        user: opac
        restart: always
        depends_on:
            - opac_mongo
            - redis-cache
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - opac_webapp-data:/app
        links:
            - opac_mongo:opac-mongo
            - redis-cache:redis-cache
        environment:
            - OPAC_DEBUG_MODE=False
            - OPAC_MONGODB_NAME=opac
            - OPAC_DATABASE_DIR=/app/data
            - OPAC_SECRET_KEY=s3kr3tk3y
            - OPAC_MONGODB_HOST=opac-mongo
            - OPAC_CACHE_ENABLED=True
            - OPAC_CACHE_DEFAULT_TIMEOUT=3600
            - OPAC_CACHE_REDIS_HOST=redis-cache
            - OPAC_SERVER_NAME=opac.scielo.org
            - OPAC_AUDIT_LOG_NOTIFICATION_ENABLED=True
            - OPAC_AUDIT_LOG_NOTIFICATION_RECIPIENTS=foo@scielo.org,bar@scielo.org
            - OPAC_RQ_REDIS_HOST=redis-cache
            - OPAC_RQ_REDIS_PORT=6379

    minio:
        image: 'minio/minio:RELEASE.2024-06-29T01-20-47Z'
        container_name: opac_minio
        hostname: opac-minio
        ports:
            - '9000:9000'
            - '9001:9001'
        environment:
            - MINIO_ROOT_USER=
            - MINIO_ROOT_PASSWORD=
        volumes:
            - '../minio/data:/data'
        command: server --console-address ":9001" /data

volumes:
  redis-data:
    driver: local
  mongodb-data:
    driver: local
  opac_webapp-data:
    driver: local